- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS
- ros_topic_name: "/ur5_shoulder_pan_joint/cmd_pos"
  gz_topic_name: "/model/ur5_rg2/joint/shoulder_pan_joint/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/ur5_shoulder_lift_joint/cmd_pos"
  gz_topic_name: "/model/ur5_rg2/joint/shoulder_lift_joint/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/ur5_elbow_joint/cmd_pos"
  gz_topic_name: "/model/ur5_rg2/joint/elbow_joint/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/ur5_wrist_1_joint/cmd_pos"
  gz_topic_name: "/model/ur5_rg2/joint/wrist_1_joint/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/ur5_wrist_2_joint/cmd_pos"
  gz_topic_name: "/model/ur5_rg2/joint/wrist_2_joint/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/ur5_wrist_3_joint/cmd_pos"
  gz_topic_name: "/model/ur5_rg2/joint/wrist_3_joint/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/rg2_finger_joint1/cmd_pos"
  gz_topic_name: "/model/ur5_rg2/joint/rg2_finger_joint1/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/rg2_finger_joint2/cmd_pos"
  gz_topic_name: "/model/ur5_rg2/joint/rg2_finger_joint2/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
